astropy/astropy-workshop

- README.md
* Change presenter for Quantities, Units, Constants to David Shupe
* Change presenter for Astropy Tables to Erik Tollerud
* Increase Tables duration from 15 to 30 minutes
* Decrease WCS duration from 45 minutes to 30 minutes
> Schedule adjustments triggered by presenter unavailability

- 00-Install_and_Setup/check_env.py
- 00-Install_and_Setup/environment.yml
- 09-Photutils/image_psf_photometry_withNIRCam.ipynb
I added some clarifying comments in the **09-Photutils/image_psf_photometry_withNIRCam** notebook about how `imexam` can be used.  I moved the entire section of imexam to the end of the notebook (just before the exercises) and labeled it as optional, which it really is.   I also added some notes on the requirements for ds9 and how XPA must also be installed.
> Clarify how imexam works 

- 00-Install_and_Setup/README.md
Fixed the pip upgrading information in the README to include --pre, recommended by @bsipocz due to astroquery's "still messed up version numbering"
> Quick tweak to installation README (proper pip upgrade instructions)

- 00-Install_and_Setup/README.md
- 00-Install_and_Setup/UPDATING.md
Made a small tweak to the README file (adding a missing command line prompt) and added a file with instructions for UPDATING the installation.  This is provided in case some workshop participants installed everything before the final tweaks were made, including the recently added specutils tutorials.
> Instructions for updating the directory and the environment 

- 00-Install_and_Setup/README.md
- README.md
Fixed typo in link to updating instructions from README.md. Link doesn't work on file system that is 'case sensitive' (including github). Can you push this through @eteq ?
> Fixed typo in link to updating instructions from README

- 08-WCS/WCS_tutorial.ipynb
Just some clarifications to the language in the WCS tutorial exercises, specifically, it was giving different paths in the markdown than in the python cell.  The markdown was referring to a non-existent file.
> Clarify some of the language in the final exercises of the WCS tutorial.

- README.md
This addresses the question raised in #56 of how to put the "community" discussions before the end of the day when people might start leaving.
This change puts it right after lunch, as a second round of more "lecture" style stuff like at the start (vs the other parts which are more tutorial-y).  The down-side is that it results in photutils and specutils being at the very end, which is perhaps appropriate as they combine material from all the early sessions, but are also a bit more technically complex (before they were split up by the break to make it a bit easier to manage the transition).
(This would complete the first step of #65)
> adjust schedule to move up community-description sessions

- 00-Install_and_Setup/README.md
- 00-Install_and_Setup/UPDATING.md
- 00-Install_and_Setup/check_env.py
- 00-Install_and_Setup/environment.yml
Fix #72 . Anaconda full install is overkill, so I also changed the instructions to point to Miniconda.
Here is an example `check_env.py` output from an env created with this patch using `conda` 4.7.12:
```
(astropy-workshop) % python check_env.py 
Found IPython 7.9.0
Found cython 0.29.13
Found jupyter 
Found notebook 6.0.2
Found numpy 1.17.3
Found scipy 1.3.1
Found skimage 0.15.0
Found matplotlib 3.1.1
Found pandas 0.25.3
Found bs4 4.8.1
Found keyring 
Found html5lib 1.0.1
Found xlwt 1.3.0
Found requests 2.22.0
Found jupyterlab 2.0.0a1
Found astropy 4.0rc1
Found asdf 2.4.2
Found gwcs 0.11.0
Found photutils 0.7.1
Found specutils 0.6
Found glue_vispy_viewers 0.12.2
Found glue 0.15.6
Found astroquery 0.4.dev0
Your Python environment is good to go!
```
> Update install instructions

- 03-UnitsQuantities/Astropy_Units.ipynb
- 03-UnitsQuantities/Astropy_Units_Solutions.ipynb
Changes to the "Astropy Units, Quantities, and Constants" section include but not limited to:
* Adding a table of contents to show you that there is more materials that 30 minutes can possibly cover, especially if including the PDF slides (9 pages) beforehand.
* Added new materials for constants science state.
* Completely removed the "little h" example at the end, as we won't have time for it anyway.
* Clarified the formula for Exercise 3 Part 2. (This is an Astropy workshop, not an astronomy test.)
* Grammatical fixes.
* Minor code clean-ups.
> Edits to Astropy Units, Quantities, and Constants

- 00-Install_and_Setup/environment.yml
I think... Tagging Adrian just to make sure the CI failures are expected.
> No longer needs astropy 4.0rc

- 01-IntroCoC/README.md
- 03-UnitsQuantities/README.md
- 04-Coordinates/README.md
- 05-FITS/README.md
- 06-Tables/README.md
- 07-Models/README.md
- 08-WCS/README.md
- 09-Photutils/README.md
- 09b-Specutils/README.md
- 10-WrapUp/README.md
- README.md
Fix #96 
* Add missing README files
* Remove instructors listing because they are already listed in root-level README
* Fill in missing authors as "unknown" -- If you know who they are, please comment on this PR or open follow-up PRs if this one is already merged
> MNT: Clean-up README files to be more consistent

- 00-Install_and_Setup/README.md
I followed the environment installation and activation instruction on my Mac, however, to activate an environment is a different command to Windows (which is the example given in the instructions). Note I used the full version of conda as I had it already installed.
> update environment activation instructions

- 00-Install_and_Setup/00_UPDATE_EMAIL.md
Fixes #121 
Add the contents of the email to send to registered participants on 2020-Jan-03, the day before the workshop. Correct the room number to 301B. Refer to the updating instructions and note they may have to do it right before the workshop.
> Add the contents of the day-before email to participants

- .circleci/config.yml
CircleCI used to pass on Linux but failed on Windows. Attempting to fix Windows broke both. Due to lack of resources, let's just revert this back to when Linux used to work and completely disable Windows testing for now.
Fix #112
> TST: Revert to when Linux worked and disable Windows

- 00-Install_and_Setup/README.md
Several people this morning encountered a problem that their notebook was picking up an older `astropy` version from the Anaconda `base` environment. Hopefully this will help troubleshoot such problems in future workshops.
> Update notebook instruction in setup

- 05-FITS/io_fits_ascii_overview.ipynb
This fixes a bug in the FITS notebook, where `.remove` should not have raised an exception when header keyword is nonexistent.
> FITS header.remove with ignore_missing

- 00-Install_and_Setup/README.md
Some people tried to include the `%` in their copy-paste and encountered obscure errors as a result.
> Clarify the prompt in command line examples

- 03-UnitsQuantities/Astropy_Units.ipynb
- 03-UnitsQuantities/Astropy_Units_Solutions.ipynb
Sorry it's *AFTER* the workshop but better late than never, right?
I've added an example exercise that uses the Astropy units equivalencies functionality.
> Added exercise to Units and Quantities notebook that uses unit equivalencies

- 00-Install_and_Setup/environment.yml
I just pushed out a quick specutils 1.1.1 that addresses #155 .  This PR then closes #155 by updating to make that version a requirement for the workshop.
I'll add a follow-on PR that updates the content, since some of the workshop attendees will have already run the install instructions and need to update, but that's separate from this PRs immediate fix of #155
> update specutils version to 1.1.1

- 00-Install_and_Setup/check_env.py
- 00-Install_and_Setup/environment.yml
- 09-Photutils/gaussian_psf_photometry.ipynb
- 09-Photutils/image_psf_photometry_withNIRCam.ipynb
- 09-Photutils/photutils_extended.ipynb
- 09-Photutils/photutils_local_backgrounds.ipynb
- 09-Photutils/photutils_overview.ipynb
- 09-Photutils/photutils_overview_solutions.ipynb
This PR updates the Photutils notebooks, including:
* Improved text and examples
* Added a new Exercise in the overview notebook
* Required `photutils 1.1.0`
* Fixed deprecations (e.g., from numpy)
> Update Photutils notebooks

- README.md
Update the schedule on the top-level README.
* Transfer presenters from the planning document
* Move Visualizing Images to afternoon session before ccdproc
* Add Cosmology presentation to morning session
* Propose that @larrybradley do the closing communities (but I can do it if need be)
I think we had a lot of time for ccdproc in the last edition -- I think the afternoon organization will flow better.
cc @bmorris3 @rosteen @nstarman @larrybradley
> Set the schedule for AAS 238 workshop

- 09-Photutils/photutils_overview.ipynb
This PR removes a cell that uses `!cat` to view a file on disk.  This fails for windows users (reported in today's workshop for the first time!) because `cat` is a linux command.  I've simply removed this cell because it's not that important.
> Remove cell for viewing file on disk

- 09c-Ccdproc/convenience_functions.py
This should fix the CI errors for the `09c-Ccdproc` `01-ccdproc-overview.ipynb` and `02-image-combination.ipynb` notebooks.
> Fix ccdproc notebook errors

- 00-Install_and_Setup/README.md
This re-jiggers the instructions to recommend using WSL on windows instead of the native windows application (and simplifies the instruction by removing some of the "if windows do X if on linux/mac do Y" clauses)
> WSL instructions

- 02b-OOP/intro_to_oop.ipynb
- 03-UnitsQuantities/Astropy_Units.ipynb
- 06-Tables/Advanced_Tables.ipynb
- 11-Cosmology/Astropy_Cosmology.ipynb
- 11-Cosmology/Astropy_Cosmology_Solutions.ipynb
- 12-ASDF/Solutions_intro_asdf.ipynb
When I teach the OOP tutorial, I always mention that the `LightCurve` object created in the notebook is only meant for pedagogical purposes. I suggest that if you want to do real research with light curves, you would benefit greatly from using the `lightkurve` package.
In this PR, I put that commentary into text in the notebook.
> Mention lightkurve in OOP intro

- 00-Install_and_Setup/check_env.py
- 00-Install_and_Setup/environment.yml
- 00-Install_and_Setup/requirements.txt
- 02b-OOP/intro_to_oop.ipynb
- 06-Tables/Tables.ipynb
- 12-ASDF/Introduction_to_ASDF.ipynb
The OOP notebook linked to the `SkyCoord` source's docstring on GitHub, using the link to specific lines in `main`, which have since moved. This PR uses a permalink instead.
Update: I've added some bugfixes to this PR to get the tests green.
> Fix link in OOP tutorial

- 06-Tables/Tables.ipynb
This PR fixes an inconsistency and some minor formatting errors. It also hides a deprecation warning thrown by the method `show_in_notebook()`.
> Fix inconsistencies and hide warnings in Tables.ipynb

- 00-Install_and_Setup/requirements.txt
- 09b-Specutils/Specutils_analysis.ipynb
- 09b-Specutils/Specutils_analysis_solutions.ipynb
CI is currently failing on both specutils analysis notebooks because a data file is assumed to exist when it does not. I've added lines to ensure that the necessary file download happens no matter when a given notebook runs.
> Bugfixes for data downloads in specutils analysis notebooks

- 09b-Specutils/Specutils_overview.ipynb
- 09b-Specutils/Specutils_overview_solutions.ipynb
CI currently fails because GWCS expects `world_to_pixel` transformations of 1D spectral coordinates using the astropy `SpectralCoords`, rather than a `Quantity`.
> bugfix: world_to_pix in gwcs via SpectralCoords

- 09-Photutils/01-aperture_basics.ipynb
- 09-Photutils/01-aperture_exercise_solution.py
- 09-Photutils/01-aperture_exercise_solution_plot.py
- 09-Photutils/02-aperture_extended.ipynb
- 09-Photutils/03-aperture_local_bkgsub.ipynb
- 09-Photutils/04-segmentation.ipynb
- 09-Photutils/04-segmentation_exercise2_solution.py
- 09-Photutils/05-psf_photometry.ipynb
> Forwardport PR 261 to main (ALOHA 2024: Clean up photometry contents)

- 09-Photutils/01-aperture_basics.ipynb
- 09-Photutils/05-psf_photometry.ipynb
This PR:
* Adds a seed to the noise image for reproducibility in the PSF photometry notebook
* Updates the aperture notebook to show sky coordinates when a WCS is passed to `aperture_photometry` (requires 2.1.0+)
Closes #268.
> Updates to photutils notebooks

- 00-Install_and_Setup/SciServer.md
This PR adds a Markdown file with instructions for using the NAVO workshop image on SciServer, to create and run a container, and install the workshop materials and packages into it.
Fixes: #270
> Add instructions for using SciServer, as a backup

- 00-Install_and_Setup/README.md
This is a quick update to the install instructions to reflect the latest guidance from the NF infrastructure team and various others that `miniforge` is safer than conda for general users since it will not trigger the commercial license of the Anaconda defaults channel.
> update for miniforge
