astropy/astropy-workshop

05-FITS/FITS-files-demo.ipynb
Notebook containing commands used during live demo
=> Added FITS files demo from live workshop

07-Models/Modeling.ipynb
Added new examples to the modeling notebook and extended the descriptions inside the notebook 
In adding the updated examples I also added more wording to describe things in the notebook. 
Also, I merged the examples of how to find and use things in the modeling and fitting packages with the examples themselves, to make it flow more like how someone might explore the package while they were trying to do something. 
@eteq @nden please take a hard look at what I've done and provide comments?
=> Update for modeling notebook for #12

06-Tables/Advanced_Tables.ipynb, 07-Models/Modeling.ipynb, README.md
I have updated the README.md file to reflect the particulars of the workshop (NOTE: I have NO CLUE as to the schedule during the day of the workshop).  
I also fixed some bugs in the Advanced Tables notebook, which was apparently using deprecated versions of make_random_gaussians_table and make_random_gaussians_image from photutils.
=> Edits to prepare for the Workshop at the 2019 Seattle AAS Meeting

README.md
I tentatively signed up for these three, but am willing to switch if we need coverage on other topics or someone wants to teach one of these.
=> clare signed up for python intro, tables, and WCS.

SETUP.md
I made a check list for workshop prep: SETUP.md
=> Setup checklist

02-PythonIntro/05. Modules.ipynb
I added a brief intro to NumPy arrays and why they're useful for scientific computing, as well as a very brief introduction to matplotlib, used to show a 2D numpy array.  This addresses #7.
=> introduction to numpy, matplotlib

README.md
=> README: Update date/time/venue

README.md
Follow up of #63 
Bonus: Use HTTPS in links.
=> Mention template in README

README.md
This PR updates the instructor names for the 2020 AAS Workshop.  Below are the folks assigned sections.  Please check off your name here to confirm you've looked at this and are ok with it.
=> Update schedule with AAS 2020 workshop instructors

README.md
https://www.youtube.com/watch?v=CdqoNKCCt7A
=> Don't forget about me

SETUP.md
=> Update facilitator setup

09-Photutils/gaussian_psf_photometry.ipynb, 09-Photutils/image_psf_photometry_withNIRCam.ipynb, 09-Photutils/photutils_extended.ipynb, 09-Photutils/photutils_local_backgrounds.ipynb, 09-Photutils/photutils_overview.ipynb
Improvements and updates for the latest version of Photutils.
I still need to make some updates to `image_psf_photometry_withNIRCam.ipynb` to programmatically download the data, but I'll do that in a separate PR.
EDIT:
Fixes #85
Fixes #86
Fixes #87
=> Update Photutils notebooks

README.md
=> Update other tools in README

00-Install_and_Setup/README.md
I had an issue with "Kernel Error" on my Windows 10 machine. It was fixed by https://github.com/jupyter/notebook/issues/4079#issuecomment-429651480 . This PR adds the relevant instructions.
=> Add one more step to install

09-Photutils/image_psf_photometry_withNIRCam.ipynb
The required simulated data are now downloaded programmatically.
=> Update photutils image-based PSF notebook

04-Coordinates/astropy_coordinates.ipynb, 04-Coordinates/astropy_coordinates_solutions.ipynb
~~I got a bit carried away and rewrote the coordinates tutorial! I kept most of the concepts, but swapped out the HCG stuff with some Gaia examples to build up to using proper motion and velocity data. The last section uses FITS and WCS to display an image, but I don't think we'll get there in the time I have, so that can just be an exercise for the attendees for their own time.~~
~~I haven't yet updated the solutions notebook (the astropy_coordinates.ipynb currently contains the solutions in case anyone has the strength to review this!).~~
This PR now just updates the solutions notebook.
This fixes #84
=> Update coordinates notebook

00-Install_and_Setup/00_INSTALL_EMAIL.md
The contents of this email will be sent by bcc: to registered workshop participants on Dec 18 or 19.
* Pre-workshop survey
* Installation instructions
* Contacting us with problems or questions
=> Add contents of mid-December install and survey email

README.md
Follow-on from #90 .  This does not necessarily close #90, as there's still a possibility of one more change (see last line in https://github.com/astropy/astropy-workshop/issues/65#issuecomment-566724138), but it might be sufficient if the time series stuff ends up not getting added.
=> Update schedule based on feedback from presenters

00-Install_and_Setup/environment.yml
@nicole-crumpler0230 , if you use this YAML file instead ot set up your environment, does the error go away? You might need to delete the previously generated env you reported in #120 first; use `conda env list` command to check. Thanks!
Fix #120 , as suggested by @astrofrog
=> Install glue with conda due to bottleneck

09-Photutils/image_psf_photometry_withNIRCam.ipynb, 09-Photutils/photutils_overview_solutions.ipynb
Part of #112 . If there is a nicer way to do this, please let me know.
=> TST: Fix photutils solution CI failures

03-UnitsQuantities/Astropy_Units.ipynb, 03-UnitsQuantities/Astropy_Units_Solutions.ipynb, 04-Coordinates/astropy_coordinates.ipynb, 05-FITS/io_fits_ascii_overview.ipynb, 06-Tables/Advanced_Tables.ipynb, 06-Tables/Tables.ipynb, 06-Tables/Tables_solutions.ipynb
The first batch of copy edits to the AAS workshop materials as per Issue #109 
Copy edited notebooks in this PR include:
03-UnitsQuantities/Astropy_Units.ipynb ✔️
03-UnitsQuantities/Astropy_Units_Solutions.ipynb ✔️
04-Coordinates/astropy_coordinates.ipynb ✔️
04-Coordinates/astropy_coordinates_solutions.ipynb ✔️
05-FITS/io_fits_ascii_overview.ipynb ✔️
06-Tables/Advanced_Tables.ipynb ✔️
06-Tables/Tables.ipynb ✔️
06-Tables/Tables_solutions.ipynb ✔️
=> Copy edit AAS workshop materials batch 1

Dockerfile, README.md
Addresses #106 
* Place files in root directory to make the repo work with mybinder.org
* Add a "launch binder" badge 
TODO:
EDIT: Revised the plan
=> Enable mybinder.org to install the environment

03-UnitsQuantities/Astropy_Units.ipynb, 05-FITS/io_fits_ascii_overview.ipynb
I am just going to merge this without review due to time constraint.
=> Final edits for units and io

.circleci/config.yml, 09b-Specutils/Specutils_analysis.ipynb
=> Fix typo and set default values so specutils_analysis executes

.circleci/config.yml, 00-Install_and_Setup/README.md
Add this change to the new `main` default branch.
=> Add instructions to ensure the correct astropy version

09c-Ccdproc/01-ccdproc-overview.ipynb
Last change to the first notebook. I'll have a brief image combination notebook in the morning.
=> Add directory processing example

02b-OOP/generate_lcs.py, 02b-OOP/intro_to_oop.ipynb
Fixes #145, #150, #159.
Introduces object oriented programming, with a simple research-motivated example of creating a `LightCurve` class. See [here](https://github.com/bmorris3/astropy-workshop-geneva-2019/blob/master/11-Extras/intro_to_oo.ipynb) for a rendered version of the notebook in this PR.
=> Adding object-oriented programing demo in new dir 02b

09c-Ccdproc/01-ccdproc-overview.ipynb, 09c-Ccdproc/02-image-combination.ipynb
@stargaser - This is the last of the changes for the ccdproc section of the tutorial.
=> Last of ccdproc section changes

09b-Specutils/Specutils_analysis.ipynb, 09b-Specutils/Specutils_overview.ipynb
This updates the specutils notebooks to reflect some changes that have happened in specutils since the last time we ran the workshop (i.e., fix some bugs!)
=> update specutils tutorial for changes since last workshop

02b-OOP/intro_to_oop.ipynb
Replace the `%%bash` magic with `%run` magic in the OOP notebook.
Fixes #171
=> Replace bash magic with run magic

09c-Ccdproc/01-ccdproc-overview.ipynb, 09c-Ccdproc/02-image-combination.ipynb
This PR 
+ fixes some typos,
+ adds a bit more explanation
+ adds a before and after plot to the image combination notebook
=> Update ccdproc notebooks 

README.md
* Add the meeting time and location
* Add morning, lunch and afternoon breaks
Question: should modeling come before photutils?
=> Update README with location and schedule

06-Tables/Advanced_Tables.ipynb
This notebook still fails in the "Digression: storing a Pandas Series within Astropy `Table`" section.  I don't know how to fix that.
=> Fix advance tables synthetic image creation

04-Coordinates/astropy_coordinates.ipynb
Addressing #204. This is meant as a draft for discussion.
=> Adding example time tutorial

README.md
To avoid a schedule conflict. Thanks @stargaser!
=> Trade places with David Shupe

07-Models/Modeling.ipynb
This PR corrects a call to matplotlib.plot where the independent variable was not used and this raised questions. It also adds a couple of new cells based on improvements in modeling.
@stargaser
=> address questions

00-Install_and_Setup/00_INSTALL_EMAIL.md, 00-Install_and_Setup/00_INTRO_EMAIL.md, 00-Install_and_Setup/00_UPDATE_EMAIL.md, 00-Install_and_Setup/README.md, 00-Install_and_Setup/UPDATING.md
* Revise installation instructions to use Mambaforge in place of Miniconda
* Use "mamba" instead of "conda"
* Update email texts for the date and location of AAS 241
*
Fixes #215
=> Modify installation instructions to use Mambaforge

09c-Ccdproc/01-ccdproc-overview.ipynb
=> Minor typo corrections

README.md
Feel free to comment or leave a suggestion in the diff if you'd like to claim a slot or module.
=> Readme updates for New Orleans

09b-Specutils/Specutils_analysis_solutions.ipynb, 09b-Specutils/Specutils_overview_solutions.ipynb
This adds a long-missing piece in the form of solutions to the specutils notebooks
=> Specutils solutions

00-Install_and_Setup/README.md, 00-Install_and_Setup/requirements.txt
@pllim -- can you please give this a quick look?
=> Update install to use miniforge and explain how to get the right branch

05-Photometry/01-aperture_basics.ipynb, 05-Photometry/01-aperture_exercise_solution.py, 05-Photometry/01-aperture_exercise_solution_plot.py, 05-Photometry/02-aperture_extended.ipynb, 05-Photometry/03-aperture_local_bkgsub.ipynb, 05-Photometry/04-segmentation.ipynb, 05-Photometry/04-segmentation_exercise2_solution.py, 05-Photometry/05-psf_photometry.ipynb
I think the links should also be updated in `main` but I don't have time to do that and this branch appears not able to be opened against `main` cleanly, so workshop maintainers should take note of the broken links that I fixed here.
=> ALOHA 2024: Clean up photometry contents
